name: mood_repository
description: A Dart Repository which manages the mood domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  tracking_client:
    path: ../../../tracking_client

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.2
  test: ^1.16.4
  very_good_analysis: ^6.0.0
