name: email_repository
description: A Dart Repository which manages sending emails.
version: 1.0.0

environment:
  sdk: ^3.0.6

dependencies:
  url_launcher: ^6.3.0

dev_dependencies:
  test: ^1.16.4
  very_good_analysis: 6.0.0