name: user_profile_repository
description: A Dart Repository which manages user data.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

dependencies:
  amplify_auth_cognito: ^2.4.0
  amplify_flutter: ^2.4.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.1
  test: ^1.25.8
  very_good_analysis: ^6.0.0