include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "lib/models/*"
    - "lib/amplifyconfiguration.dart"
    - "lib/firebase_options.dart"
    - "lib/amplify_outputs*"
